name: ci

on:
  push:
    branches:
      - 'master'

jobs:
  image-build-push:
    runs-on: ubuntu-latest
    steps:
      -
        name: deploy started, notify to discord
        env:
          DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
          DISCORD_USERNAME: Roxy Deploy Hooker
          DISCORD_EMBEDS: [${{ secrets.DISCORD_EMBED }}]
        uses: Ilshidur/action-discord@master
      -
        name: login to irohub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.IROHUB_URL }}
          username: ${{ secrets.IROHUB_USERNAME }}
          password: ${{ secrets.IROHUB_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.IROHUB_URL }}/roxy-blog:latest
  
  reload:
    needs: image-build-push
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    -
      name: pull and apply
      uses: appleboy/ssh-action@v0.1.6
      with: 
        host: ${{ secrets.MASTER_HOST }}
        username: ${{ secrets.MASTER_USERNAME }}
        password: ${{ secrets.MASTER_PASSWORD }}
        port: ${{ secrets.MASTER_PORT }}
        script: cd ${{ secrets.ROXY_DEP_PATH }} && ${{ secrets.ROXY_DEP }}
    -
      name: deploy finish, notify to discord
      env:
        DISCORD_WEBHOOK: ${{ secrets.DISCORD_WEBHOOK }}
        DISCORD_USERNAME: Roxy Deploy Hooker
        DISCORD_EMBEDS: [${{ secrets.DISCORD_EMBED }}]
      uses: Ilshidur/action-discord@master

