name: ci

# v 태그가 붙은 push 가 일어날 경우만 트리거
on:
  push:
    branches:
      - 'master'

# GITHUB_REF = refs/tags/v*.*.*
jobs:
  image-build-push:
    runs-on: ubuntu-latest
    steps:
      - 
        name: login to irohub
        uses: docker/login-action@v2
        with:
          registry: ${{ secrets.IROHUB_URL }}
          username: ${{ secrets.IROHUB_USERNAME }}
          password: ${{ secrets.IROHUB_TOKEN }}
      -
        name: build and push
        uses: docker/build-push-action@v3
        with:
          push: true
          tags: ${{ secrets.IROHUB_URL }}/roxy-blog:latest
